### ISSUE TITLE
Remove or document Python file in docs folder

### ISSUE THREAD

**Issue by lindsay-fredrick** [bcgov/bcstats-ses#2]
There's a python file in the docs folder that I'm not sure it's purpose. Do we need it, and if so what is it for?

**Comment by jonjunduan** [comment]
Oh. This is for create a table for the Literature review. Moved it to the LAN.

**Comment by lindsay-fredrick** [comment]
Where was this completed? It's still on the main branch, and I haven't seen an associated PR to remove it.

**Comment by lindsay-fredrick** [comment]
Fixed in merge
