### ISSUE TITLE
Document code in src folder

### ISSUE THREAD

**Issue by lindsay-fredrick** [bcgov/bcstats-ses#5]
* Although I know that you and Tim are going through and 'code reviewing' work that is already on main, we cannot currently tell (on main) what has been addressed, what has not. 

Suggestion:
* Create a README in the src file that lists which code still needs code reviewing, and/or a comment in each code script that indicates if it has been reviewed yet. As code gets reviewed, the README and any code comments can be updated as well. Any code that is deprecated can simply be deleted.

**Comment by jonjunduan** [comment]
A basic README is created and will be updated when we work through the plan.
